# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(950, 688)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn_dir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_dir.setGeometry(QtCore.QRect(0, 0, 181, 141))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_dir.setFont(font)
        self.btn_dir.setObjectName("btn_dir")
        self.list_files = QtWidgets.QListWidget(self.centralwidget)
        self.list_files.setGeometry(QtCore.QRect(0, 140, 181, 571))
        self.list_files.setObjectName("list_files")
        self.image = QtWidgets.QLabel(self.centralwidget)
        self.image.setGeometry(QtCore.QRect(180, 0, 541, 571))
        self.image.setObjectName("image")
        self.btn_left = QtWidgets.QPushButton(self.centralwidget)
        self.btn_left.setGeometry(QtCore.QRect(790, 140, 161, 31))
        self.btn_left.setObjectName("btn_left")
        self.btn_right = QtWidgets.QPushButton(self.centralwidget)
        self.btn_right.setGeometry(QtCore.QRect(790, 180, 161, 31))
        self.btn_right.setObjectName("btn_right")
        self.miror_1 = QtWidgets.QPushButton(self.centralwidget)
        self.miror_1.setGeometry(QtCore.QRect(790, 220, 161, 31))
        self.miror_1.setObjectName("miror_1")
        self.btn_bw = QtWidgets.QPushButton(self.centralwidget)
        self.btn_bw.setGeometry(QtCore.QRect(790, 250, 161, 31))
        self.btn_bw.setObjectName("btn_bw")
        self.btn_kontrast = QtWidgets.QPushButton(self.centralwidget)
        self.btn_kontrast.setGeometry(QtCore.QRect(790, 290, 161, 31))
        self.btn_kontrast.setObjectName("btn_kontrast")
        self.btn_blur = QtWidgets.QPushButton(self.centralwidget)
        self.btn_blur.setGeometry(QtCore.QRect(790, 330, 161, 31))
        self.btn_blur.setObjectName("btn_blur")
        self.btn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_1.setGeometry(QtCore.QRect(790, 380, 161, 31))
        self.btn_1.setObjectName("btn_1")
        self.btn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn_2.setGeometry(QtCore.QRect(790, 420, 161, 31))
        self.btn_2.setObjectName("btn_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ФОто редактор"))
        self.btn_dir.setText(_translate("MainWindow", "Папка"))
        self.image.setText(_translate("MainWindow", "Картинка"))
        self.btn_left.setText(_translate("MainWindow", "поворот в ліво"))
        self.btn_right.setText(_translate("MainWindow", "поворот в право"))
        self.miror_1.setText(_translate("MainWindow", "Дзеркально зліва направо"))
        self.btn_bw.setText(_translate("MainWindow", "Чорно біла"))
        self.btn_kontrast.setText(_translate("MainWindow", "Контраст"))
        self.btn_blur.setText(_translate("MainWindow", "блюр"))
        self.btn_1.setText(_translate("MainWindow", "поворот в право"))
        self.btn_2.setText(_translate("MainWindow", "поворот в право"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
